debug: true
packs:
  lobbypack: 
   # The url the client should download the resourcepack from.
   # Has to be a direct download link! No medifaire/mega/other oneclick-hoster!
    url: http://example.com/lobbyresourcepack.zip
   # The sha1 hash of the resourcepack's zip file, 
   # if not correct the client will waste bandwidth but it will still work!
    hash: aadw32ead
  gamepack:
    url: http://example.com/minigameresourcepack.zip
    hash: daw0mpwa0dp
global:
  pack: lobbypack
servers:
  lobby:
    pack: lobbypack
  minigame:
    pack: gamepack