debug: true
default-language: en
disable-metrics: false
autogeneratehashes: false
append-hash-to-url: true
usepack-is-temporary: true
stored-packs-override-assignments: false
permanent-pack-remove-time: 30
use-auth-plugin: false
jedis:
  host: localhost
  password: "password"
#empty:
#  url: http://cdn.moep.tv/files/Empty.zip
#  hash: 01517226212d27586ea0c5d6aff1aa5492dd2484
#  uuid: 90a7e280-0c24-36e2-b39b-327abf49c261
#global:
#  pack: globalpack
#  send-delay: 20
servers:
  skyblock:
    pack: skyblock
    regex: "skyblock-.*-.*"
useauth: false
packs:
  #globalpack:
  #  url: http://example.com/globalpack.zip
  #  uuid: be201d94-62f7-3ec2-8104-1e68a817b29d
  #  hash: abcdef012345678abcdef012345678abcdef0123
  #  restricted: false
  #  permission: velocityresourcepacks.pack.globalpack
  skyblock:
    url: https://farmeurimmo.fr
    uuid: bcba1733-f595-3ede-8983-9267ffea97f5
    hash: 8a7ae8252dbf870ff3db7132b967cca079d054dd
    restricted: false