debug: true
# Default language
default-language: en
# Whether or not resourcepack file hashes should be generated on startup:
autogeneratehashes: true
# Whether /usepack should apply packs temporary or permanent when run without any argument:
usepack-is-temporary: true
# When manually setting a permanent pack then it will be reset if the user disconnects in under x amount of seconds.
# 0 or anything below will disable this functionality
permanent-pack-remove-time: 30
packs:
  lobbypack: 
   # The url the client should download the resourcepack from.
   # Has to be a direct download link! No medifaire/mega/other oneclick-hoster!
    url: http://example.com/lobbyresourcepack.zip
   # The sha1 hash of the resourcepack's zip file, 
   # if not correct the client will waste bandwidth but it will still work!
   # At least that's what the Minecraft wiki says... (Site: Server.properties#Minecraft_server_properties)
    hash: abcdef012345678abcdef012345678abcdef0123
   # The format version of this resourcepack
   # 1 is for 1.8 packs
   # 2 is for 1.9-1.10
   # 3 is for 1.11-1.12
   # 4 is for 1.13 and above
    format: 1
   # Whether or not this pack will only be send to players with a certain permission
   # permission: bungeeresourcepacks.pack.<packname>
    restricted: false
   # If you want you can define a specific permission for this pack if you don't want
   # the default bungeeresourcepacks.pack.<packname> permission!
    permission: bungeeresourcepacks.pack.lobbypack
  gamepack:
    url: http://example.com/minigameresourcepack.zip
    hash: 012345678abcdef012345678abcdef012345678a
# Empty pack to reset the pack to the default one
empty:
  url: http://cdn.moep.tv/files/Empty.zip
  hash: c05faed4680570a6159823e13fbae2ae830166ab
global:
  # List of packs to not replace if the user already has them
  # If no main pack is set the first one also gets used to reset 
  # the pack if the user has a non secondary one
  # Also this list will be used to select a pack if a user does not have the permission
  # or the right version to use that pack. (From top to bottom)
  # secondary:
  # - lobbypack
  # Delay in ticks before sending the pack to a player after he logs in/switches to the server
  send-delay: 20
servers:
  lobby:
    pack: lobbypack
    secondary:
    - gamepack
  minigame:
    pack: gamepack
    # Use a regex to target all servers with a certain name
    regex: 'minigame_.*'